/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: azzamah (https://sketchfab.com/azzamah)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/130ec74a08b2445c91aae106d738d01e
title: Card
*/

import * as THREE from "three";
import React, { useRef, useMemo } from "react";
import { useLoader } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  const texture = useMemo(
    () => new THREE.TextureLoader().load(props.cardType),
    [props.cardType]
  );

  const group = useRef();
  const { nodes, materials } = useLoader(GLTFLoader, "./card/scene.gltf");

  const material = new THREE.MeshPhysicalMaterial({ map: texture });
  //<group position={[1.1, 4.19, 0]} scale={[4.24, 0.63, 4.24]}>
  //<group position={[-0.26, -6.63, 0]} scale={[0.24, 1.58, 0.24]}></group>
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[-6.1, -9, 6]}>
        <mesh
          material={material}
          geometry={nodes.mesh_0.geometry}
          castShadow
          metalness={8}
        />
        <mesh
          material={materials.Card3initialSha}
          geometry={nodes.mesh_1.geometry}
          castShadow
        />
        <mesh
          material={material}
          geometry={nodes.mesh_2.geometry}
          castShadow
          metalness={8}
        />
      </group>
    </group>
  );
}
